version: '3.9'

services:
  teacher-api-nestjs:
    container_name: teacher-api-nestjs
    build: .
    expose:
      - "3000"
    depends_on:
      - mysql-nestjs

  mysql-nestjs:
    image: mysql:8.0
    container_name: mysql-nestjs
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: class
      MYSQL_USER: thanhnt2930
      MYSQL_PASSWORD: thanhnt2930
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - teacher-api-nestjs

volumes:
  mysql_data:
